name:  Dev Report
description: Template para reportar historias de usuario con criterios de aceptaci贸n y tareas de desarrollo
title: "[HU]: "
labels: ["dev", "enhancement"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: Historia de Usuario
      description: |
        **Como** usuario
        **Quiero** lograr algo
        **Para** obtener un beneficio
      value: |
        **Como** 
        **Quiero** 
        **Para**
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Criterios de Aceptaci贸n
        Define las condiciones que deben cumplirse para considerar completada esta historia.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de Aceptaci贸n
      description: Lista los criterios que deben cumplirse
      value: |
        - [ ] Criterio 1
        - [ ] Criterio 2
        - [ ] Criterio 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Tareas de Desarrollo

  - type: textarea
    id: dev-tasks
    attributes:
      label: Tareas
      description: Lista de tareas t茅cnicas para implementar la historia
      value: |
        - [ ] Tarea 1
        - [ ] Tarea 2
        - [ ] Tarea 3
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notas Adicionales
      description: Cualquier informaci贸n adicional o contexto relevante
      placeholder: "A帽ade contexto, referencias, tecnicismos, o consideraciones especiales..."
      render: markdown
    validations:
      required: false
